In [74]:
import pandas as pd
import numpy as np

df=pd.read_csv("queue_management_refactored-general.csv")

In [75]:
df.head()

,customer_id,facility_id,arrival_time,age,service_type,priority_level,customer_type,wait_tolerance,queue_length,queue_position,...,hour_of_day,day_of_week,is_holiday,peak_hours,no_show_indicator,service_counters,operational_hours,feedback_score,actual_wait_time,queue_status
0,C000001,F001,21-01-2024 09:01,53,complaint,normal,online,11,28,8,...,9,6,0,1,0,6,12,4.3,29.2,critical
1,C000002,F002,03-01-2024 11:14,21,application,normal,walk-in,28,39,13,...,11,2,0,1,0,5,10,4.1,45.5,critical
2,C000003,F001,07-01-2024 13:06,66,consultation,elderly,online,12,10,6,...,13,6,0,0,0,5,8,2.7,14.8,congested
3,C000004,F004,27-01-2024 18:39,42,renewal,elderly,walk-in,19,9,1,...,18,5,0,0,0,4,12,4.7,5.0,normal
4,C000005,F002,12-01-2024 10:23,44,renewal,elderly,walk-in,11,23,23,...,10,4,0,1,0,5,12,4.0,10.0,busy

In [76]:
df.tail()

,customer_id,facility_id,arrival_time,age,service_type,priority_level,customer_type,wait_tolerance,queue_length,queue_position,...,hour_of_day,day_of_week,is_holiday,peak_hours,no_show_indicator,service_counters,operational_hours,feedback_score,actual_wait_time,queue_status
9995,C009996,F001,22-01-2024 11:14,79,consultation,elderly,online,14,16,12,...,11,0,0,1,0,5,9,4.4,31.1,critical
9996,C009997,F004,15-01-2024 18:05,39,renewal,urgent,appointment,5,11,2,...,18,0,1,0,0,6,8,5.0,2.4,normal
9997,C009998,F004,16-01-2024 09:08,31,renewal,normal,online,24,9,3,...,9,1,0,1,0,4,9,4.2,4.2,normal
9998,C009999,F004,08-01-2024 13:05,80,renewal,elderly,online,11,14,9,...,13,0,0,0,0,6,12,4.1,26.8,critical
9999,C010000,F001,02-01-2024 13:55,32,payment,elderly,walk-in,13,20,10,...,13,1,0,0,0,6,9,4.4,12.5,busy

In [77]:
print(df.shape)

(10000, 24)

In [78]:
print(df.columns)

Index(['customer_id', 'facility_id', 'arrival_time', 'age', 'service_type',
       'priority_level', 'customer_type', 'wait_tolerance', 'queue_length',
       'queue_position', 'historical_avg_wait', 'active_staff_count',
       'avg_service_time', 'staff_availability', 'hour_of_day', 'day_of_week',
       'is_holiday', 'peak_hours', 'no_show_indicator', 'service_counters',
       'operational_hours', 'feedback_score', 'actual_wait_time',
       'queue_status'],
      dtype='object')

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          10000 non-null  object
 1   facility_id          10000 non-null  object
 2   arrival_time         10000 non-null  object
 3   age                  10000 non-null  int64
 4   service_type         10000 non-null  object
 5   priority_level       10000 non-null  object
 6   customer_type        10000 non-null  object
 7   wait_tolerance       10000 non-null  int64
 8   queue_length         10000 non-null  int64
 9   queue_position       10000 non-null  int64
 10  historical_avg_wait  10000 non-null  float64
 11  active_staff_count   10000 non-null  int64
 12  avg_service_time     10000 non-null  float64
 13  staff_availability   9961 non-null   float64
 14  hour_of_day          10000 non-null  int64
 15  day_of_week          10000 non-null  int64
 16  is_holiday           10000 non-null  int64
 17  peak_hours           10000 non-null  int64
 18  no_show_indicator    10000 non-null  int64
 19  service_counters     10000 non-null  int64
 20  operational_hours    10000 non-null  int64
 21  feedback_score       10000 non-null  float64
 22  actual_wait_time     9966 non-null   float64
 23  queue_status         10000 non-null  object
dtypes: float64(5), int64(12), object(7)
memory usage: 1.8+ MB

In [80]:
df.describe()

,age,wait_tolerance,queue_length,queue_position,historical_avg_wait,active_staff_count,avg_service_time,staff_availability,hour_of_day,day_of_week,is_holiday,peak_hours,no_show_indicator,service_counters,operational_hours,feedback_score,actual_wait_time
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0000,9961.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,9966.000000
mean,54.439400,16.486700,20.004000,10.437200,23.633810,3.576900,10.6370,0.803961,13.030800,2.774700,0.070400,0.357700,0.114000,3.99540,9.762500,3.840640,34.286805
std,21.119871,7.402142,11.048185,8.569061,10.635845,1.981484,6.1063,0.106438,3.142871,2.010409,0.255833,0.479347,0.317827,1.42863,1.492085,0.889833,35.754082
min,18.000000,5.000000,3.000000,1.000000,6.000000,1.000000,3.0000,0.600000,8.000000,0.000000,0.000000,0.000000,0.000000,2.00000,8.000000,1.000000,0.000000
25%,36.000000,11.000000,12.000000,4.000000,15.600000,2.000000,5.8000,0.720000,10.000000,1.000000,0.000000,0.000000,0.000000,3.00000,8.000000,3.400000,7.000000
50%,55.000000,16.000000,18.000000,8.000000,21.600000,3.000000,9.0000,0.820000,13.000000,3.000000,0.000000,0.000000,0.000000,4.00000,10.000000,4.000000,21.100000
75%,73.000000,21.000000,25.000000,14.000000,28.800000,4.000000,14.5000,0.880000,16.000000,5.000000,0.000000,1.000000,0.000000,5.00000,12.000000,4.500000,50.100000
max,90.000000,54.000000,58.000000,56.000000,58.500000,8.000000,30.0000,1.000000,18.000000,6.000000,1.000000,1.000000,1.000000,6.00000,12.000000,5.000000,120.000000

In [81]:
df.isnull().sum()

customer_id             0
facility_id             0
arrival_time            0
age                     0
service_type            0
priority_level          0
customer_type           0
wait_tolerance          0
queue_length            0
queue_position          0
historical_avg_wait     0
active_staff_count      0
avg_service_time        0
staff_availability     39
hour_of_day             0
day_of_week             0
is_holiday              0
peak_hours              0
no_show_indicator       0
service_counters        0
operational_hours       0
feedback_score          0
actual_wait_time       34
queue_status            0
dtype: int64

In [82]:
print(df.duplicated().sum())

0

In [83]:
for column in df.columns:
  print(column)
  print(df[column].unique())
  print("----------------------------------------------------------------------------")

customer_id
['C000001' 'C000002' 'C000003' ... 'C009998' 'C009999' 'C010000']
----------------------------------------------------------------------------
facility_id
['F001' 'F002' 'F004' 'F003' 'F005']
----------------------------------------------------------------------------
arrival_time
['21-01-2024 09:01' '03-01-2024 11:14' '07-01-2024 13:06' ...
 '15-01-2024 18:05' '16-01-2024 09:08' '08-01-2024 13:05']
----------------------------------------------------------------------------
age
[53 21 66 42 44 46 81 83 88 82 57 85 45 24 77 25 87 48 62 31 50 27 76 60
 58 90 39 84 54 71 86 49 32 56 64 63 78 79 33 47 36 52 70 69 74 67 80 30
 41 34 61 26 29 75 65 35 20 40 28 51 43 22 23 68 59 19 73 55 72 38 18 37
 89]
----------------------------------------------------------------------------
service_type
['complaint' 'application' 'consultation' 'renewal' 'payment' 'inquiry']
----------------------------------------------------------------------------
priority_level
['normal' 'elderly' 'urgent']
----------------------------------------------------------------------------
customer_type
['online' 'walk-in' 'appointment']
----------------------------------------------------------------------------
wait_tolerance
[11 28 12 19 24  9 13 14  8 21  7  6 18 16 26 46 27 17  5 10 25 23 22 33
 36 29 31 32 15 37 34 35 20 38 30 40 39 41 42 45 43 54]
----------------------------------------------------------------------------
queue_length
[28 39 10  9 23 15 17 26  6 14 12 24 21 32 18 16 11 20  5  8 34 19 22 31
 25  7 27 37 36 44  4 43 42 49 30 46 29 56 13 41 45 53 51  3 35 58]
----------------------------------------------------------------------------
queue_position
[ 8 13  6  1 23 14 15  3 19  9  7  2  4 11 10  5 27 18 26 30 32 12 17 24
 20 33 21 39 22 35 16 31 40 36 37 43 34 25 29 28 38 46 48 56 44 52 42 41
 45 47 53 50 54 51 55 49]
----------------------------------------------------------------------------
historical_avg_wait
[32.8 41.4 27.3 22.1 21.6 11.  14.  14.3 16.9 34.2 17.  16.  30.6 45.
 24.  18.  19.8 18.2 23.4 53.8 13.  19.  36.  28.8 20.  31.2 32.4 25.2
 15.  12.  43.2 25.  10.  44.5 16.2 37.8 20.8 23.  25.9 29.9 58.5 24.7
 39.6 22.  32.5 15.6 51.5 39.8 21.  25.7 13.2 19.5  9.6 28.6  6.  28.1
 35.1 22.7 42.1  8.4 23.8 56.2 30.4 11.4 27.  10.8 10.2 46.8 49.1 18.4
  7.8 26.  13.8  9.  15.1  7.2 37.4  6.6 12.6 19.4 11.9 17.3 24.8 20.5
 14.4]
----------------------------------------------------------------------------
active_staff_count
[8 4 3 7 2 1 6 5]
----------------------------------------------------------------------------
avg_service_time
[19.9 12.7  8.3  5.   3.  12.3 20.3  3.8  4.8  5.4 10.6 10.3  8.5  4.6
 23.3  7.4  8.   9.5 19.8  9.1  3.2 18.5  6.   8.8 11.5  6.2  4.3 13.6
 13.7  4.9 16.5 24.9 12.5 10.8  5.7 14.2  7.  16.8  6.5 10.5  6.6 23.8
  8.4  9.   8.6  3.5 16.1 19.1  8.2 16.3 10.7 13.   6.1 18.3  5.3  9.9
 10.1 18.8 14.5  5.1 13.3 21.3 24.4  3.4  9.4 14.6 25.7  4.7 14.3 26.7
  8.7 13.9 14.9  7.6  6.8 19.2 16.6  5.6  7.1 10.9  3.7  5.9  5.2 11.6
  4.  20.  17.   8.9 18.7 11.9 21.8 15.2  7.8 23.1  9.7 17.2 12.6 14.1
 27.5  6.9  6.3 17.6 18.9 14.4  4.2 14.8 14.7  9.8 11.1 16.4 11.2 15.7
 18.  11.7 11.3 17.1 18.6 22.3 19.4  7.2 16.2 22.5 23.5 21.7 19.  22.9
 11.4 12.1 15.9 11.  28.9  5.8 24.5 15.8  6.7  8.1 16.9 12.8 10.   9.6
 22.8 15.1 12.9  4.5 20.9 13.2 15.3  7.5 14.   3.3 13.1 19.7  6.4 13.5
 24.7  3.1 17.7 21.1 18.2  3.9 17.8 20.2  3.6 24.3 27.3 27.9  4.1 17.5
  7.9  9.2 12.2 16.7  7.3 22.2  9.3 23.  18.1 25.2 20.7 12.4 28.  13.8
 25.6 15.6 11.8 27.4 21.4 25.   5.5 10.4 22.1 17.4 19.6 20.6  7.7 18.4
 15.5 16.  10.2 26.9 26.4 23.7 19.5 23.2 15.4 19.3 30.  20.4 15.  17.3
 26.3 22.6 24.1 26.  13.4 21.2 29.7 21.5 24.8 20.1  4.4 20.5 23.9 25.1
 21.6 21.  24.  21.9 23.4 24.6 24.2 17.9 28.5 27.6 25.5 25.9 23.6 12.
 27.7 28.8 20.8 22.  29.5 25.4 22.7 27.8 29.1 27.2 25.3 26.6 28.3 29.9
 28.6 29.6 25.8 26.1 27.1 22.4 29.  26.2 29.3 28.4 29.8 28.2 26.5 29.2
 26.8 27. ]
----------------------------------------------------------------------------
staff_availability
[0.82 0.89 0.84 0.9  0.93 0.85 0.64 0.65  nan 0.63 0.81 0.96 0.62 0.92
 0.79 0.74 0.95 0.77 0.83 0.97 0.61 0.7  0.69 0.94 0.87 0.67 0.88 0.78
 0.76 0.99 0.68 0.72 0.86 0.8  0.91 0.73 0.71 1.   0.98 0.66 0.6  0.75]
----------------------------------------------------------------------------
hour_of_day
[ 9 11 13 18 10 15 12  8 16 14 17]
----------------------------------------------------------------------------
day_of_week
[6 2 5 4 1 0 3]
----------------------------------------------------------------------------
is_holiday
[0 1]
----------------------------------------------------------------------------
peak_hours
[1 0]
----------------------------------------------------------------------------
no_show_indicator
[0 1]
----------------------------------------------------------------------------
service_counters
[6 5 4 2 3]
----------------------------------------------------------------------------
operational_hours
[12 10  8  9]
----------------------------------------------------------------------------
feedback_score
[4.3 4.1 2.7 4.7 4.  3.1 2.5 5.  4.8 3.2 3.7 3.  2.9 4.4 3.9 3.5 2.6 4.2
 3.4 3.8 4.9 3.6 4.6 1.  1.7 4.5 2.8 2.4 3.3 2.3 2.2 1.5 2.  1.6 1.4 1.8
 1.2 1.9 2.1 1.1 1.3]
----------------------------------------------------------------------------
actual_wait_time
[ 29.2  45.5  14.8 ... 107.3  98.9 104.4]
----------------------------------------------------------------------------
queue_status
['critical' 'congested' 'normal' 'busy' 'error' 'abandoned']
----------------------------------------------------------------------------

In [84]:
print(df["actual_wait_time"].describe())

count    9966.000000
mean       34.286805
std        35.754082
min         0.000000
25%         7.000000
50%        21.100000
75%        50.100000
max       120.000000
Name: actual_wait_time, dtype: float64

In [85]:
df.to_csv("clear_dataset.csv", index=False)

Replace missing values

In [86]:
df["staff_availability"] = df["staff_availability"].fillna(
    df["staff_availability"].median()
)

In [87]:
df = df.dropna(subset=["actual_wait_time"])

changing data type

In [88]:
df["arrival_time"] = pd.to_datetime(
    df["arrival_time"],
    format="%d-%m-%Y %H:%M"
)

In [89]:
df.head()

,customer_id,facility_id,arrival_time,age,service_type,priority_level,customer_type,wait_tolerance,queue_length,queue_position,...,hour_of_day,day_of_week,is_holiday,peak_hours,no_show_indicator,service_counters,operational_hours,feedback_score,actual_wait_time,queue_status
0,C000001,F001,2024-01-21 09:01:00,53,complaint,normal,online,11,28,8,...,9,6,0,1,0,6,12,4.3,29.2,critical
1,C000002,F002,2024-01-03 11:14:00,21,application,normal,walk-in,28,39,13,...,11,2,0,1,0,5,10,4.1,45.5,critical
2,C000003,F001,2024-01-07 13:06:00,66,consultation,elderly,online,12,10,6,...,13,6,0,0,0,5,8,2.7,14.8,congested
3,C000004,F004,2024-01-27 18:39:00,42,renewal,elderly,walk-in,19,9,1,...,18,5,0,0,0,4,12,4.7,5.0,normal
4,C000005,F002,2024-01-12 10:23:00,44,renewal,elderly,walk-in,11,23,23,...,10,4,0,1,0,5,12,4.0,10.0,busy

In [90]:
df.loc[:, "arrival_time"] = pd.to_datetime(
    df["arrival_time"],
    format="%d-%m-%Y %H:%M"
)

notebook 3

In [91]:
categorical_columns = [
    "facility_id",
    "service_type",
    "priority_level",
    "customer_type",
    "queue_status"
]

In [92]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for column in categorical_columns:
    df[column] = encoder.fit_transform(df[column])

In [93]:
X = df.drop(["actual_wait_time", "customer_id"], axis=1)
y = df["actual_wait_time"]

In [94]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.2,

    random_state=42

)

In [95]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

DTypePromotionError: The DType <class 'numpy.dtypes.DateTime64DType'> could not be promoted by <class 'numpy.dtypes.Float64DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.DateTime64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Int64DType'>, <class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.Int64DType'>)